### ISSUE TITLE
Guice error with maven 3.0.4, maven site and asciidoctor-maven-plugin 1.5.3

### ISSUE THREAD

**Issue by tcollignon** [asciidoctor/asciidoctor-maven-plugin#203]
I have the following error, if I want to generate a Maven site with asciidoctor-maven-plugin 1.5.3 with maven 3.0.4 (I haven't with maven 3.3.9).

```
[INFO] --- maven-site-plugin:3.4:site (default-cli) @ asciidoctor-with-maven-site-example ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.7
[INFO] Relativizing decoration links with respect to project URL: http://maven.apache.org
[INFO] Rendering site with org.apache.maven.skins:maven-fluido-skin:jar:1.4 skin.
[INFO] Skipped "About" report (maven-project-info-reports-plugin:2.7:index), file "index.html" already exists for the English version.
[INFO] Rendering 1 Doxia document: 1 asciidoc
io/console not supported; tty will not be manipulated
Feb 08, 2016 6:53:01 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: org.asciidoctor.maven.site.AsciidoctorParser
com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.apache.maven.project.MavenProject was bound.
  while locating org.asciidoctor.maven.site.AsciidoctorParser

1 error
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1018)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at java.util.AbstractMap.get(AbstractMap.java:187)
        at org.apache.maven.doxia.parser.manager.DefaultParserManager.getParser(DefaultParserManager.java:46)
        at org.apache.maven.doxia.DefaultDoxia.getParser(DefaultDoxia.java:72)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:341)
        at org.apache.maven.doxia.siterenderer.DoxiaDocumentRenderer.renderDocument(DoxiaDocumentRenderer.java:51)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:129)
        at org.apache.maven.plugins.site.render.SiteMojo.renderDoxiaDocuments(SiteMojo.java:261)
        at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:172)
        at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

You can reproduce with this project : https://github.com/tcollignon/asciidoctor-with-maven-site-example and this command : 

```
mvn site:site
```

If you can't reproduce, juste modify _index.adoc_ and relaunch maven command.

**Comment by tcollignon** [comment]
Note that I haven't this error with asciidoctor-maven-plugin 1.5.3-SNAPSHOT (probably without https://github.com/abelsromero/asciidoctor-maven-plugin/commit/83785615673817726c4b6dbe9039cf1a877f4e01)

**Comment by mojavelinux** [comment]
I did some testing and verified the Asciidoctor site plugin requires at least Maven 3.2.2 (in theory, 3.2.1 should work, but there's some other issue going on). Earlier versions of Maven are not supported. I found no documentation on the Maven site that explains to me how I can support earlier versions of Maven, so unfortunately I don't know how to do it.

I recommend using the Maven Wrapper to manage the version of Maven used for your builds. It's an awesome way to get everyone using the same version of Maven (just like the Gradle Wrapper).

See http://jakub.marchwicki.pl/posts/2015/06/04/maven-wrapper/

I followed those discussion and had the latest version of Maven working in the build with almost no effort.

**Comment by mojavelinux** [comment]
@abelsromero We should probably document the minimum required version of Maven for the site plugin in the README.

**Comment by mojavelinux** [comment]
Everything from 3.2.2 to 3.3.9 (the latest release) works fine in my tests.

**Comment by tcollignon** [comment]
Hi Dan, 

Thank you for your feedback, I understand that's difficult to have compatibilities with Maven 3.0.X, if you add Maven requirments in REAMDE it's perferct for me
