### ISSUE TITLE
Version 1.5.3 incompatible with maven-site-plugin 3.5 and higher; injection error

### ISSUE THREAD

**Issue by ljnelson** [asciidoctor/asciidoctor-maven-plugin#280]
Hello; if I use the `maven-site-plugin` version 3.4, I am able to add a `<dependencies>` stanza to its configuration that pulls in the `asciidoctor-maven-plugin` 1.5.3 just fine.

If I use version 3.5 or higher, I get a very dramatic looking Guice error from deep within the `maven-site-plugin` somewhere.

I have no asciidoc files or anything yet; this is simply after adding the relevant `<dependency>` stanza.

Here is a relevant section of my `pom.xml` as reported by `mvn help:effective-pom`, edited for (some) brevity:

     <plugin>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.5</version>
        
        <dependencies>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctor-maven-plugin</artifactId>
            <version>1.5.3</version>
            <scope>compile</scope>
          </dependency>
        </dependencies>
        
      </plugin>

Here is a sample of the (absolutely ginormous) stack trace related to Sisu-emulating-Plexus-over-Guice injection failing (I'll meet you at the bottom of the stack trace):

    [INFO] --- maven-site-plugin:3.5:site (default-site) @ my-project ---
    [WARNING] Error injecting: org.apache.maven.doxia.siterenderer.DefaultSiteRenderer
    java.lang.NoClassDefFoundError: org/apache/maven/doxia/sink/impl/XhtmlBaseSink
    	at java.lang.ClassLoader.defineClass1(Native Method)
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
    	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    	at java.lang.ClassLoader.defineClass1(Native Method)
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
    	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    	at java.lang.Class.getDeclaredMethods0(Native Method)
    	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    	at java.lang.Class.getDeclaredMethods(Class.java:1975)
    	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:688)
    	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
    	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:164)
    	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:613)
    	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:569)
    	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:555)
    	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:884)
    	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
    	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
    	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
    	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1006)
    	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1038)
    	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
    	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
    	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
    	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
    	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
    	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
    	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
    	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
    	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
    	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
    	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
    	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
    	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
    	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
    	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
    	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
    	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
    	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
    	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
    	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
    	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
    	at org.eclipse.sisu.plexus.PlexusRequirements$RequirementProvider.get(PlexusRequirements.java:250)
    	at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:48)
    	at org.eclipse.sisu.bean.BeanInjector.injectMembers(BeanInjector.java:52)
    	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:140)
    	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
    	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
    	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
    	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
    	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
    	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
    	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
    	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
    	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
    	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
    	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
    	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
    	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
    	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
    	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
    	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
    	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
    	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
    	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
    	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
    	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
    	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
    	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
    	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
    	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
    	at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
    	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
    	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
    	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
    	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
    	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
    	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: java.lang.ClassNotFoundException: org.apache.maven.doxia.sink.impl.XhtmlBaseSink
    	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    	... 121 more
    [WARNING] Error injecting: org.apache.maven.plugins.site.render.SiteMojo

I'll use version 3.4 I guess as a workaround.  Thanks in advance for looking into this!

**Comment by abelsromero** [comment]
As it is right now, asciidoctor-maven-plugin is not compatible with never versions of the maven-site.
Seems that the new version is not backward compatiblae and the integration with doxia needs to be adapted to doxia 1.7.

**Comment by abelsromero** [comment]
Ok, good news...bad news.
- Good news: it's absolutely easy to fix. The problem is a compilation issue, ver 1.7 removed backward compatibilty classes, we only need to delete the `AsciidoctorSiteModule` and update the version in the pom. It works for both maven-site 3.4 and 3.5.
- Bad news: this means breaking compatibility with previous versions of the plugin.

Honestly, I don't see a problem with it.

**Comment by abelsromero** [comment]
Since 1.6.0 already contains other non backward compatible changes, I am also scheduling this for 1.6.0.

**Comment by mosabua** [comment]
Is this coming some time soon?

**Comment by abelsromero** [comment]
I fear not.
There's no scheduled release date for 1.6.0, and right now the core [Asciidoctor] (https://github.com/asciidoctor/asciidoctor) next release will be 1.5.6.

To be clear, this change means that maven-site-plugin will only work with 3.4 (released July 2014) and above.
I wanted to join all 'compatibility breaking' changes in 1.6.0, but if there's enough demand we can add this into next release. @mojavelinux wdyt?

**Comment by mojavelinux** [comment]
I think it's worth breaking compatibility since, technically, the compatibility breakage started in the site plugin. When upgrading to Asciidoctor Maven Plugin 1.5.6, it's reasonable to ask people to also update the site plugin. If they don't want to, they can continue to use the Asciidoctor Maven Plugin 1.5.5 and update the version of AsciidoctorJ.

**Comment by abelsromero** [comment]
:+1:  At the latest I can make the changes during the weekend.

**Comment by mosabua** [comment]
Cool.. I just wanted to upgrade the site plugin (for other reasons) and could not do that because I rely on the the asciidoctor plugin .. imho it would be fine if the latest asciidoctor maven plugin needs the latest site plugin .. for reference https://github.com/simpligility/android-maven-plugin/blob/master/pom.xml#L796
