### ISSUE TITLE
Custom TreeProcessor makes maven build fail for pdf output

### ISSUE THREAD

**Issue by gbm-bailleul** [asciidoctor/asciidoctor-maven-plugin#343]
I have a project using a specific TreeProcessor, I have this issue when I try to generate a PDF (no issue in html5):

    Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `numbered_title' 
    for #<Java::OrgAsciidoctorAst::SectionImpl:0xca647ca>
    Did you mean?  numbered
    at RUBY.block in layout_toc_level(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor
    -pdf/converter.rb:2354)
    at RUBY.block in theme_font(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor
    pdf/converter.rb:2931)
    at RUBY.block in font(uri:classloader:/gems/prawn-2.2.2/lib/prawn/font.rb:62)
    at RUBY.save_font(uri:classloader:/gems/prawn-2.2.2/lib/prawn/font.rb:215)

I guess the exception is raised in this part of my TreeProcessor (no need to put something in the loop):

    for (AbstractBlock block: document.getBlocks()) {
    }

Removing the processor or commenting this block makes the build end with no error.

I am using:
* org.asciidoctor:asciidoctor-maven-plugin:jar:1.5.6
* org.jruby:jruby-complete:jar:9.1.8.0:runtime
* org.asciidoctor:asciidoctorj:jar:1.5.6:compile
* org.asciidoctor:asciidoctorj-pdf:jar:1.5.0-alpha.16:runtime

I saw asciidoctor/asciidoctor-maven-plugin#298 , but it did not help so much. 

I guess it is a dependency issue but I fail to fix it.

**Comment by abelsromero** [comment]
I am having a different issue on Windows, but I am also experiencing issues with PDF.

Can you share some info on the environment and the document you are parsing?

**Comment by abelsromero** [comment]
Good news, I just got my test to run using AsciidoctorJ `1.6.0-alpha.6`.

Note that you will need to adapt the extension because the API has been greatly improved and that forced us to make some non-compatible changes. But under the hood it runs the same Asciidoctor core and is reliable, just...some method names may change.

**Comment by gbm-bailleul** [comment]
I am currently working on windows. 

I migrated to 1.6.0-alpha.6.
Not so difficult, just replacing DocumentRuby and AbstractNode (and mocking some disappeared method for the test).

I have now an exception when the plugin is loaded (see exception below).

My extensions are loaded from configuration defined in the pom. I guess this method is not compatible with 1.6.0-X when using maven plugin in version  1.5.6.

Snip of the pom:

    <executions>
    	<execution>
    		<id>Document generation</id>
    		<goals>
    		    <goal>process-asciidoc</goal>
    		</goals>
    		<phase>generate-resources</phase>
    		<configuration>
    			<sourceDirectory>docs/asciidoc</sourceDirectory>
    			<sourceDocumentName>full.adoc</sourceDocumentName>
    			<backend>pdf</backend>
    			<extensions>
    				<extension>
    					<c lassName>com.wline.documentation.ref.RequirementMacro</className>
        				<blockName>req</blockName>
    				</extension>
    			</extensions>
    			<attributes>
    				<csv>${working.references.dir}/${artifactId}.csv</csv>
    				<pdf-stylesdir>../style</pdf-stylesdir>
   				<pdf-style>custom</pdf-style>
    			</attributes>
    		</configuration>
    	</execution>
    


The exception:


``
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (Document generation) on project archiving-documentation: Unexpected exception while registering extensions
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected exception while registering extensions
	at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:210)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected exception while registering extensions
	at org.asciidoctor.maven.extensions.AsciidoctorJExtensionRegistry.register(AsciidoctorJExtensionRegistry.java:95)
	at org.asciidoctor.maven.extensions.AsciidoctorJExtensionRegistry.register(AsciidoctorJExtensionRegistry.java:76)
	at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:208)
	... 23 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.asciidoctor.maven.extensions.AsciidoctorJExtensionRegistry.register(AsciidoctorJExtensionRegistry.java:92)
	... 25 more
Caused by: java.lang.NoClassDefFoundError: org/asciidoctor/ast/ContentNode
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.jruby.javasupport.binding.Initializer$2.computeValue(Initializer.java:452)
	at org.jruby.javasupport.binding.Initializer$2.computeValue(Initializer.java:449)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at org.jruby.javasupport.binding.Initializer.getMethods(Initializer.java:486)
	at org.jruby.javasupport.binding.ClassInitializer.setupClassMethods(ClassInitializer.java:116)
	at org.jruby.javasupport.binding.ClassInitializer.initialize(ClassInitializer.java:31)
	at org.jruby.javasupport.binding.Initializer.setupProxyClass(Initializer.java:104)
	at org.jruby.javasupport.Java.createProxyClass(Java.java:528)
	at org.jruby.javasupport.Java.generateClassProxy(Java.java:486)
	at org.jruby.javasupport.Java.createProxyClassForClass(Java.java:442)
	at org.jruby.javasupport.JavaSupportImpl$3.computeValue(JavaSupportImpl.java:125)
	at org.jruby.javasupport.JavaSupportImpl$3.computeValue(JavaSupportImpl.java:117)
	at org.jruby.util.collections.MapBasedClassValue.get(MapBasedClassValue.java:25)
	at org.jruby.javasupport.JavaSupportImpl.getProxyClassFromCache(JavaSupportImpl.java:202)
	at org.jruby.javasupport.Java.getProxyClass(Java.java:409)
	at org.jruby.javasupport.Java.getProxyClass(Java.java:402)
	at org.jruby.javasupport.Java.get_proxy_class(Java.java:394)
	at org.jruby.javasupport.JavaUtilities.get_proxy_class(JavaUtilities.java:34)
	at org.jruby.javasupport.JavaUtilities$INVOKER$s$1$0$get_proxy_class.call(JavaUtilities$INVOKER$s$1$0$get_proxy_class.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
	at org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:141)
	at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:179)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
	at org.jruby.runtime.Block.yield(Block.java:167)
	at org.jruby.RubyArray.collect(RubyArray.java:2478)
	at org.jruby.RubyArray.map19(RubyArray.java:2492)
	at org.jruby.RubyArray$INVOKER$i$0$0$map19.call(RubyArray$INVOKER$i$0$0$map19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:497)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:298)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
	at org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.evalScriptlet(Ruby.java:482)
	at org.jruby.Ruby.evalScriptlet(Ruby.java:458)
	at org.asciidoctor.extension.JavaExtensionRegistry.javaImport(JavaExtensionRegistry.java:218)
	at org.asciidoctor.extension.JavaExtensionRegistry.blockMacro(JavaExtensionRegistry.java:162)
	... 30 more
Caused by: java.lang.ClassNotFoundException: org.asciidoctor.ast.ContentNode
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 89 more
``

**Comment by abelsromero** [comment]
Not sure why it fails, but it should work. I doubt it, but I'd say that it did not update to the new AsciidoctorJ version and run on 1.5.6.
Still you can use the SPI interface as in my example. If you can share a project that mimics your code we can work on that.

**Comment by gbm-bailleul** [comment]
Oups, my bad.

The dependency added in my pom was commented. Now I really use the 1.6.0-X

... and I have a completely different exception:
```
Caused by: org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error (SystemCallError) 123 - FindFirstFile
```
Complete stack below

I will push my error on github later today with some details on how to fail.


```
''org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (Document generation) on project archiving-documentation: Execution Document generation of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: (SystemCallError) Unknown error (SystemCallError) 123 - FindFirstFile
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution Document generation of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: (SystemCallError) Unknown error (SystemCallError) 123 - FindFirstFile
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error (SystemCallError) 123 - FindFirstFile
	at RUBY.symlink?(uri:classloader:/jruby/kernel/file.rb:141)
	at RUBY.<module:Prawn>(uri:classloader:/gems/prawn-2.2.2/lib/prawn.rb:11)
	at RUBY.<main>(uri:classloader:/gems/prawn-2.2.2/lib/prawn.rb:9)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at RUBY.(root)(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:3)
	at RUBY.<main>(uri:classloader:/jruby/kernel/kernel.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at RUBY.require_relative(uri:classloader:/jruby/kernel/kernel.rb:13)
	at RUBY.<main>(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf.rb:3)
```

**Comment by abelsromero** [comment]
Never seen that.
Can you provide an example with both extension and document? 
Does running an empty extension fails?

**Comment by gbm-bailleul** [comment]
OK
The new issue has no link with the extension.
I still have the error without the extension.
So I guess using 1.6.0 and rewriting helped.

**Comment by abelsromero** [comment]
I am not able to reproduce it.
I am really sorry to insist again, but unless you can provide a concrete example I am unable to see what is the issue is.
