### ISSUE TITLE
JRuby error message: (NoMethodError) undefined method `divmod' for nil:NilClass

### ISSUE THREAD

**Issue by McAviti** [asciidoctor/asciidoctor-maven-plugin#371]
I am not sure whether this problem originates from a version change of the plugin components or a problem with my adoc files (which are quite many). I expereimented with older plugin/JRuby versions and with a minimal adoc file, with no success. Also changing the backend didn't help.

Strange thing is that a rollback to the last version that worked (about two months ago) did not help either. In the meantime I installed Ruby on my windows machine, but deinstalled it now again - so hopefully there is no interdependence.

This is the output of the script:
```
Okt 22, 2018 11:51:56 AM org.asciidoctor.internal.JRubyAsciidoctor renderFile
SCHWERWIEGEND: (NoMethodError) undefined method `divmod' for nil:NilClass
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.615 s
[INFO] Finished at: 2018-10-22T11:51:56+02:00
[INFO] Final Memory: 43M/445M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc (generate-docx) on project documentation: Execution generate-docx of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `divmod' for nil:NilClass -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc (generate-docx) on project documentation: Execution generate-docx of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `divmod' for nil:NilClass
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-docx of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `divmod' for nil:NilClass
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `divmod' for nil:NilClass
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:371)
	at org.asciidoctor.maven.AsciidoctorMojo.renderFile(AsciidoctorMojo.java:463)
	at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:247)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 22 more
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `divmod' for nil:NilClass
	at RUBY.block in int_to_roman(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:225)
	at org.jruby.RubyHash.each(org/jruby/RubyHash.java:1350)
	at org.jruby.RubyEnumerable.map(org/jruby/RubyEnumerable.java:830)
	at RUBY.int_to_roman(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:224)
	at RUBY.sectnum(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/section.rb:118)
	at RUBY.sectnum(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/section.rb:116)
	at RUBY.block in outline(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:306)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
	at RUBY.outline(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:301)
	at RUBY.block in outline(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:311)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
	at RUBY.outline(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:301)
	at RUBY.document(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:177)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1141)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1515)
	at RUBY.block in convert_file(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1171)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589)
	at RUBY.convertFile(<script>:78)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

My current config (of the latest try):
```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <asciidoctor.maven.plugin.version>1.5.7.1</asciidoctor.maven.plugin.version>
        <asciidoctorj.version>1.5.7</asciidoctorj.version>
        <asciidoctorj.diagram.version>1.5.9</asciidoctorj.diagram.version>
        <jruby.version>9.1.17.0</jruby.version>
        <snippetsDirectory>${project.build.directory}/generated-snippets</snippetsDirectory>
    </properties>
```

Any direction to what might be wrong is appreciated.
thanx,
~klemensd

**Comment by abelsromero** [comment]
Q: What version of Java are you using?

Other than that, I don't see anything strange, so it could be related to some specific document. Could you share a test project that reproduces the issue?

**Comment by McAviti** [comment]
Hi @abelsromero , thankx for your answer.

A: Java it was not the problem (I tried with multiple JDK versions of 8 and 10, though)

In the process of very slowly stripping down my docs in order to get a minimal reproducable package I found the issue in this line:
```
= image:images/bdlogo.png[] J... documentation
```
Without the image in the header marker it now works. At another place the header in conjunction with an image seems to do no harm:
```
= image:images/arc42-logo.png[arc42] J.... System Documentation
```
This works flawlessly.
Maybe you have an idea about what's asciidoctors (or JRuby's) problem with that. If I can help to further reproduce it once again, please tell me.

My problem is solved, thanx again,
~klemens

**Comment by abelsromero** [comment]
I am glad you could solve it. With the info I'll try to reproduce it and if I can't, also using native Ruby.

> A: Java it was not the problem (I tried with multiple JDK versions of 8 and 10, though)

All those versions are supported. Java 11 requires jRuby 9.2.1.0 which should be released very soon.

**Comment by mojavelinux** [comment]
The call to divmod is seen in the integer to roman numeral conversion. I don't expect that to be called in this case, so I'll have to dig in to see what's going on.

**Comment by mojavelinux** [comment]
Oh, I see. That conversion is used to assign a number to a part.

**Comment by mojavelinux** [comment]
I can't seem to reproduce this problem. Are you able to reproduce it using the [asciidoc-to-html-example](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoc-to-html-example) in the examples project? Perhaps there's a configuration I'm not considering. Specifically, I'm wondering if the AST is ever modified. The `@number` property should never be nil, which makes me wonder if perhaps something is manipulating it.

**Comment by McAviti** [comment]
Hi Dan @mojavelinux 

I succeeded to reproduce this problem. Not the logo causes it, the error shows at a certain combination of (wrong) heading sequence, having a (in my example) level 3 header, then the level 1, and a level 3 again, with section numbering on. Like so:

```
:sectnums:

= Example Manual
Doc Writer <doc.writer@example.org>
2014-09-09
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]

This is a user manual for an example project.

== Introduction

=== blah

= Sunset

=== fish

This project does something.
We just haven't decided what that is yet.
```
With this at the beginning of example-manual.adoc I get the divmod error. Can you reproduce it as well?

**Comment by abelsromero** [comment]
With that example is was easy to reproduce in maven and ruby -> https://github.com/abelsromero/asciidoc-to-html-issue-sectnums

The odd things is that executing directly in Ruby, we get a message that is not shown by maven.
Even enabling the new `logHandler` it just fails abruptly.

**Comment by abelsromero** [comment]
The output from Ruby `asciidoctor -a numbered src/docs/asciidoc/reproducible-example.adoc --trace `


```
asciidoctor: ERROR: reproducible-example.adoc: line 15: level 0 sections can only be used when doctype is book
asciidoctor: WARNING: reproducible-example.adoc: line 17: section title out of sequence: expected level 1, got level 2
/Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:225:in `block in int_to_roman': undefined method `divmod' for nil:NilClass (NoMethodError)
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:224:in `each'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:224:in `map'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:224:in `int_to_roman'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/section.rb:118:in `sectnum'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/section.rb:116:in `sectnum'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:328:in `section'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38:in `convert'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:71:in `convert'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `block in content'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `map'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `content'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:349:in `section'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38:in `convert'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:71:in `convert'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `block in content'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `map'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `content'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1209:in `content'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:185:in `document'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38:in `convert'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1141:in `convert'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1515:in `convert'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `block in convert_file'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `open'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `convert_file'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `each'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/bin/asciidoctor:14:in `<top (required)>'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/bin/asciidoctor:23:in `load'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/bin/asciidoctor:23:in `<main>'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/abelsromero/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by mojavelinux** [comment]
Great work! I'll try to figure out why this leads to a nil number, fix it,
and add a test.

**Comment by mojavelinux** [comment]
This is an issue in core, so this issue can be closed (or marked as upstream). https://github.com/asciidoctor/asciidoctor/issues/2931

**Comment by McAviti** [comment]
thanks.
