### ISSUE TITLE
Asciidoctor 2.2.0 can't be used due to missing DirectoryWalker

### ISSUE THREAD

**Issue by Riduidel** [asciidoctor/asciidoctor-maven-plugin#422]
I use asciidoctor-maven-plugin on Windows with the following dependency configuration

		<asciidoctor.maven.plugin.version>1.6.0</asciidoctor.maven.plugin.version>
		<asciidoctorj.pdf.version>1.5.0</asciidoctorj.pdf.version>
		<asciidoctorj.version>2.2.0</asciidoctorj.version>
		<asciidoctorj.diagram.version>2.0.1</asciidoctorj.diagram.version>
		<jruby.version>9.2.9.0</jruby.version>
		<revealjs.version>3.8.0</revealjs.version>
		<asciidoctor.highlighter>highlightjs</asciidoctor.highlighter>
		<asciidoctor-revealjs.version>2.0.0</asciidoctor-revealjs.version>

(the full configuration is quite long)
With this configuration, I get

	[WARNING] Error injecting: org.asciidoctor.maven.AsciidoctorMojo
	java.lang.NoClassDefFoundError: org/asciidoctor/DirectoryWalker
		at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
		at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
		at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
		at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
		at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:115)
		at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:706)
		at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:930)
		at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
		at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291)
		at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222)
		at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1040)
		at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1071)
		at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1034)
		at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
		at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
		at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
		at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:57)
		at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:66)
		at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
		at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:127)
		at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
		at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
		at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
		at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
		at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
		at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
		at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
		at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
		at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
		at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:520)
		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:124)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
		at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	Caused by: java.lang.ClassNotFoundException: org.asciidoctor.DirectoryWalker
		at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
		at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
		at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
		at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
		... 52 more

Wether everything works fine when I set back asciidoctorj version to 1.6.0
Is there something I'm doing wrong ?

My maven config is

	Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
	Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin\..
	Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.2
	Default locale: fr_FR, platform encoding: Cp1252
	OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Riduidel** [comment]
Although it seems to be fixed on master. Is a release possible ?

**Comment by Riduidel** [comment]
Is it a question for @abelsromero ? For @mojavelinux ?

**Comment by abelsromero** [comment]
Sorry, I missed this one. Have you tried with version `2.0.0-RC.1.
The release candidate it's fully stable. It's labeled RC because a few non-backward-compatible changes are introduced.

**Comment by Riduidel** [comment]
Bug is visible in the RC.1, but not in the SNAPSHOT 🤔

**Comment by abelsromero** [comment]
What's puzzling me is that there's nothing in master to explain this, the error does not make much sense to me and I don't get any error with the example repo (https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoc-to-revealjs-example).

Is there any other extention or additional configuration?

**Comment by abelsromero** [comment]
Could you check the dependencies? or if you have a reproducible project that could also help?

**Comment by Riduidel** [comment]
OK, I can now confirm that either 2.0.0-RC.1 or 2.0.0-SNAPSHTO fail.
You can use https://github.com/Riduidel/agile-architecture-documentation-archetype
This is an archetype that trigger the creation of a project containing asciidoc.
You just have to run `mvn verify` in the root project to have the archetype built.
If you want to test other versions, go in `src/main/resources/archetype-respources/pom.xml` and change the `version.asciidoctor.maven.plugin` property to test other versions.

**Comment by abelsromero** [comment]
I could run the project successfully on Linux and Windows10 generating the artifact as you explained and running from the archetype directory with `mvn package`.

After assigning values to group, artifact, version and ${package} I updated the following properties.
```xml
<version.asciidoctor.maven.plugin>2.0.0-RC.1</version.asciidoctor.maven.plugin>
<version.asciidoctorj>2.2.0</version.asciidoctorj>
```
If I did not update Asciidoctorj version I got a very similar error to yours. _Could this be the thing?_
Note also it is highly advised to upgrade all other version (pdf, jruby, ...).

My Linux env 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/-/.sdkman/candidates/maven/current
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: /home/asalgadr/.sdkman/candidates/java/11.0.6.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.28-1-manjaro", arch: "amd64", family: "unix"
```

**Comment by Riduidel** [comment]
So, my version is

	$ mvn -V
	Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
	Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin\..
	Java version: 14, vendor: Oracle Corporation, runtime: C:\Program Files\OpenJDK\jdk-14
	Default locale: fr_FR, platform encoding: Cp1252
	OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Let's try with your parameters ... And damn, it works well! So I have nothing to add 🥴
