### ISSUE TITLE
(flake) org.asciidoctor.maven.http.AsciidoctorHttpServerTest.should_return_default_resource_when_url_is_root

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#735]
This test fails regularly affecting CI. Re-run works, but we need stability to reduce work and noise.

```
org.asciidoctor.maven.http.AsciidoctorHttpServerTest.should_return_default_resource_when_url_is_root -- Time elapsed: 0.047 s <<< ERROR!
java.net.BindException: Address already in use: bind
```

**Comment by abelsromero** [comment]
Similar failure, different test seen.
```
Error:  Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.59 s <<< FAILURE! -- in org.asciidoctor.maven.http.AsciidoctorHttpServerTest
Error:  org.asciidoctor.maven.http.AsciidoctorHttpServerTest.should_start_and_stop_server -- Time elapsed: 0 s <<< ERROR!
java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:380)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
